Add imsl and irdm
jcdeimos/acars_vdlm2_parser pull request #10
Opened 2024-04-14 00:14 UTC by rpatel3001

not quite ready to merge. needs tests and also maybe some function implementations.

2024-04-14 02:49 UTC, rpatel3001 commented
tests are in, some files are a bit short but there's not much variation in the tool outputs.

i did not implement a bunch of set_* and clear_* in imsl.rs and irdm.rs because I didn't see them used anywhere and a bunch of them were already unimplemented for different message types, but let me know if you want them.

2024-04-14 03:39 UTC, jcdeimos requested changes
Please address any usage of `.unwrap()` in lieu of handling any underlying errors.

2024-04-14 03:39 UTC, jcdeimos commented on src/imsl.rs
> +        Some(self.timestamp.as_ref().copied().unwrap() as f64)
Do you **_really_** want to panic if the field `timestamp` is `None`?

Could use something like this?

```
let Some(timestamp_value) = self.timestamp else {
    return None;
}
Some(timestamp_value as f64)
```

2024-04-14 03:39 UTC, jcdeimos commented on src/irdm.rs
> +        Some(NaiveDateTime::parse_from_str(&self.acars.timestamp, "%Y-%m-%dT%H:%M:%S").unwrap().and_utc().timestamp() as f64)
Another possible panic that really isn't needed?

Much prefer to see more code written to implement proper handling than just taking the easy way out.

Something like:

```
let Ok(naive_date_time) = NaiveDateTime::parse_from_str(&self.acars.timestamp, "%Y-%m-%dT%H:%M:%S") else {
    return None;
}
Some(naive_date_time.and_utc().timestamp() as f64)
```

2024-04-17 03:30 UTC, rpatel3001 commented
this is the first time I'm using rust so some of the language constructs are new to me - thanks for the sample fixes. I think the question mark operator is equivalent to what you've shown?

2024-04-17 04:04 UTC, fredclausen commented
> this is the first time I'm using rust so some of the language constructs are new to me - thanks for the sample fixes. I think the question mark operator is equivalent to what you've shown?

The question mark operator is the equivalent to what you wrote. See [this](https://stackoverflow.com/a/42921174) for a better explanation.

Basically, in most cases we don't need to send an error message all the way up the stack if something is wrong. Rust constructs like `if let Ok(value)` and `match` allow handing of exceptions gracefully.

2024-04-17 04:10 UTC, rpatel3001 commented
From what I'm reading, including that link, the question mark is equivalent to the suggested fix (if-let or match). My unwrap would have panicked but ? or if-let returns Err/None instead.

2024-04-17 05:22 UTC, jcdeimos commented
Mostly made the suggestions from a readability standpoint (especially given being new to the language), but there are indeed a number of different ways of removing the `.unwrap()` in code.

The only other question I have is to do with the irdm message. Is `acars.timestamp` _always_ going to be that format, or is it configurable?

Given that the message could be deserialised correctly (and thus be _valid_), but parsing the timestamp may fail, it'd definitely be something to emit as an error instead of potentially having a silent or misleading failure.

2024-04-17 11:35 UTC, rpatel3001 commented
The format is not configurable, it's set [here](https://github.com/muccc/iridium-toolkit/blob/0705e50c905c6801b827aafa5d9abebeba0774f0/iridiumtk/reassembler/sbd.py#L322).

There is a `%z` for timezone offset but [it's ignored](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) for naive datetimes, which [datetime.fromtimestamp](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp) without a `tz` parameter returns.

2025-04-14 21:35 UTC, fredclausen commented
@jcdeimos what is the status on this? I'm happy to fix any issues you have with it, but after (re)reading the conversation I'm not sure what you wanted done to it.

2025-04-15 10:19 UTC, jcdeimos approved these changes

2025-04-15 10:19 UTC, merged